server:
  port: 8080
jwt:
  secret: secret
  expiration: 86400000
spring:
  dataSource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/conduit
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enable: true

logging:
  level:
    org.flyway: debug

auth:
  jwt:
    secret: secret